#!/bin/bash
sudo apt-get update -y
sudo apt-get install docker.I -y
sudo ap[t-get update -y
sudo systemctl start docker -y
sudo systemctl enable docker -y 
sudo docker run -d -p 80:8080 --name wildfly-container jboss/wildfly:latest
