#!/bin/bash
sudo apt-get update -y
sudo apt-get install docker.io -y
sudo apt-get update -y
sudo systemctl start docker 
sudo systemctl enable docker  
sudo docker run -d -p 80:8080 --name wildfly-container jboss/wildfly:latest
